<a href="https://colab.research.google.com/github/Iankcool5/DSC_110/blob/main/In_class/In_Class_week_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data Prep for Machine Learning/Prediction**

In [ ]:
--This line of code imports the pandas library for data manipulation, StandardScaler from sklearn.preprocessing for feature scaling, and train_test_split from sklearn.model_selection for splitting data into training and testing sets.

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
--This line of code uses the pandas library to read a CSV file directly from a specified URL on GitHub. The data is then loaded into a pandas DataFrame named `df` for further analysis and manipulation. This is the initial step to bring the dataset into our Colab environment.

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/osoliman/DSC110/refs/heads/main/Datasets/nhanes_final.csv')

In [ ]:
-- This gives us the first 5 rows of the graph of data

In [ ]:
df.head()

,id,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes,hba1c,fasting_glucose
0,130378.0,1.0,43.0,6.0,5.0,27.0,179.5,135.0,2.0,5.6,113.0
1,130379.0,1.0,66.0,3.0,5.0,33.5,174.2,121.0,2.0,5.6,99.0
2,130380.0,2.0,44.0,2.0,3.0,29.7,152.9,111.0,1.0,6.2,156.0
3,130381.0,2.0,5.0,7.0,NaN,23.8,120.1,NaN,2.0,NaN,NaN
4,130382.0,1.0,2.0,3.0,NaN,NaN,NaN,NaN,2.0,NaN,NaN

**1- Filtering**

In [ ]:
--These next few lines are on filitering.The first two lines find the smallest age in the lirabry. The last line counts all the rows and all the columns in the table

In [ ]:
df = df[df['age'] >= 18].copy()

In [ ]:
df['age'].min()

18.0

In [ ]:
df.shape

(8153, 11)

**2- Dropping Columns**

In [ ]:
--This line code is used to drop columns in the data table. In this line we dropped id, hba1c, and fasting_glucose and as a result it alaos shows when we do df.shape which shows all the current rows and columns.

In [ ]:
df = df.drop(columns=['id', 'hba1c', 'fasting_glucose'])

In [ ]:
df.shape

(8153, 8)

**3- Data Mapping**

In [ ]:
--This line of code creates a map of different cotegories. (Gender, race and education).

In [ ]:
gender_map     = {1.0: 'Male', 2.0: 'Female'}
race_map       = {1.0: 'Mexican American', 2.0: 'Other Hispanic',
                  3.0: 'White', 4.0: 'Black',
                  6.0: 'Asian', 7.0: 'Other'}
education_map  = {1.0: 'Less than 9th', 2.0: '9-11th grade',
                  3.0: 'High school',   4.0: 'Some college',
                  5.0: 'College grad',  9.0: 'Do not know'}

#df['gender']         = df['gender'].map(gender_map)
#df['race_ethnicity'] = df['race_ethnicity'].map(race_map)
#df['education']      = df['education'].map(education_map)

In [ ]:
--These lines of code take race ethinicity and finds the genders and races of individuals in the data table. The df['education']line shows the differnet levels of eudctaion one could be in

In [ ]:
df['gender'] = df['gender'].map(gender_map)

In [ ]:
df['race_ethnicity'].head()

0    6.0
1    3.0
2    2.0
6    1.0
7    3.0
Name: race_ethnicity, dtype: float64

In [ ]:
df['race_ethnicity'] = df['race_ethnicity'].map(race_map)

In [ ]:
df['race_ethnicity']

0                   Asian
1                   White
2          Other Hispanic
6        Mexican American
7                   White
               ...
11927    Mexican American
11929               Black
11930      Other Hispanic
11931      Other Hispanic
11932               White
Name: race_ethnicity, Length: 8153, dtype: object

In [ ]:
df['education'] = df['education'].map(education_map)

In [ ]:
df['education'].head()

0    College grad
1    College grad
2     High school
6    9-11th grade
7     High school
Name: education, dtype: object

**4- Missing Values**

In [ ]:
--This line of code calculates the sum of missing (NaN) values for each column in the DataFrame `df`. It helps to quickly identify which columns have missing data and how many missing values each column contains, which is crucial for data cleaning.

In [ ]:
df.isna().sum()

gender               0
age                  0
race_ethnicity       0
education          359
bmi               1918
height_cm         1891
systolic_bp       2030
has_diabetes         3
dtype: int64

In [ ]:
df['bmi'] = df['bmi'].fillna(df['bmi'].mean())

In [ ]:
df['height_cm']   = df['height_cm'].fillna(df['height_cm'].mean())
df['systolic_bp'] = df['systolic_bp'].fillna(df['systolic_bp'].mean())

In [ ]:
df = df.dropna(subset=['education']).copy()

**5-Defining the target**

In [ ]:
-- This line of code targets a certain category and finds out the other characteristics of the people under that category.

In [ ]:
df = df[df['has_diabetes'].isin([1.0, 2.0])].copy()

In [ ]:
df['has_diabetes'] = df['has_diabetes'].map({1.0: 1, 2.0: 0})

In [ ]:
df.shape

(7523, 8)

In [ ]:
df.head()

,gender,age,race_ethnicity,education,bmi,height_cm,systolic_bp,has_diabetes
0,Male,43.0,Asian,College grad,27.000000,179.500000,135.000000,0
1,Male,66.0,White,College grad,33.500000,174.200000,121.000000,0
2,Female,44.0,Other Hispanic,High school,29.700000,152.900000,111.000000,1
6,Male,43.0,Mexican American,9-11th grade,29.659326,166.954982,122.561653,0
7,Female,65.0,White,High school,29.659326,166.954982,122.561653,0

**6- One-hot encoding**

In [ ]:
--This line of of code will target certain columsn in the data table and give either true or false if they fit that description.

In [ ]:
df = pd.get_dummies(df, columns=['gender', 'race_ethnicity', 'education'],
                    drop_first=True)

In [ ]:
df.head()

,age,bmi,height_cm,systolic_bp,has_diabetes,gender_Female,gender_Male,race_ethnicity_Asian,race_ethnicity_Black,race_ethnicity_Mexican American,race_ethnicity_Other,race_ethnicity_Other Hispanic,race_ethnicity_White,education_9-11th grade,education_College grad,education_Do not know,education_High school,education_Less than 9th,education_Some college
0,43.0,27.000000,179.500000,135.000000,2.0,False,True,True,False,False,False,False,False,False,True,False,False,False,False
1,66.0,33.500000,174.200000,121.000000,2.0,False,True,False,False,False,False,False,True,False,True,False,False,False,False
2,44.0,29.700000,152.900000,111.000000,1.0,True,False,False,False,False,False,True,False,False,False,False,True,False,False
6,43.0,29.659326,166.954982,122.561653,2.0,False,True,False,False,True,False,False,False,True,False,False,False,False,False
7,65.0,29.659326,166.954982,122.561653,2.0,True,False,False,False,False,False,False,True,False,False,False,True,False,False

**7- Scaling Numeric Values**

In [ ]:
--These lines of code identify specific numeric columns ('age', 'bmi', 'height_cm', 'systolic_bp') in the DataFrame. Then, they initialize a StandardScaler object and apply it to these columns to standardize their values. Standardization transforms the data so that it has a mean of 0 and a standard deviation of 1, which is a common preprocessing step for many machine learning algorithms.

In [ ]:
numeric_cols = ['age', 'bmi', 'height_cm', 'systolic_bp']
scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

In [ ]:
print(round(df['age'].mean(),2))

0.0

In [ ]:
df['age'].std()

1.0000664694739656

**8- Train/Test Split**

In [ ]:
--This line of code helps to divide the data into two subsets. One will train the data and the otehr will test the data to see it will perform.

In [ ]:
X = df.drop(columns=['has_diabetes'])
y = df['has_diabetes']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [ ]:
X_train.head()

,age,bmi,height_cm,systolic_bp,gender_Male,race_ethnicity_Black,race_ethnicity_Mexican American,race_ethnicity_Other,race_ethnicity_Other Hispanic,race_ethnicity_White,education_College grad,education_Do not know,education_High school,education_Less than 9th,education_Some college
6225,0.321165,0.183891,-1.310308,0.446166,False,False,False,False,False,True,False,False,True,False,False
8518,0.776425,-1.080948,-0.062021,-0.739931,False,False,False,False,False,True,False,False,True,False,False
5532,0.548795,1.885958,1.061437,0.633444,False,True,False,False,False,False,True,False,False,False,False
7314,1.459315,-0.009844,0.000959,-0.018182,False,False,False,False,False,True,False,False,False,True,False
9913,-0.987708,-0.987256,0.494034,-0.178096,True,False,False,False,True,False,False,False,False,True,False